theme: minima
title: Whisperable - Russia's secreys
author: William Bland
email: admin@whisperable.com
description: > # this means to ignore newlines until "baseurl:"
  This is the home of the Whisperable podcast with personal tales of life in Russia.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
